# Generated by Django 2.1.7 on 2019-03-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20190319_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmer',
            old_name='languages',
            new_name='language',
        ),
    ]
